/*
* AUTOGENERATED FILE. DO NOT EDIT IT
* Generated by ../../tools/js/generate_spidermonkey_bindings.py on 2012-05-29
*/

#import "js_bindings_CCRotateBy.h"

#import "js_bindings_CCActionInterval.h"

extern JSObject *JSPROXY_CCRotateBy_object;

/* Proxy class */
@interface JSPROXY_CCRotateBy : JSPROXY_CCActionInterval
{
}

@end
