/*
* AUTOGENERATED FILE. DO NOT EDIT IT
* Generated by ../../tools/js/generate_spidermonkey_bindings.py on 2012-05-29
*/

#import "js_bindings_CCSprite.h"

#import "js_bindings_CCNode.h"

extern JSObject *JSPROXY_CCSprite_object;

/* Proxy class */
@interface JSPROXY_CCSprite : JSPROXY_CCNode
{
}

@end
