/*
* AUTOGENERATED FILE. DO NOT EDIT IT
* Generated by ../../tools/js/generate_spidermonkey_bindings.py on 2012-05-30
*/

#import "js_bindings_CCScene.h"

#import "js_bindings_CCNode.h"

extern JSObject *JSPROXY_CCScene_object;
extern JSClass *JSPROXY_CCScene_class;

/* Proxy class */
@interface JSPROXY_CCScene : JSPROXY_CCNode
{
}

@end
