/*
* AUTOGENERATED FILE. DO NOT EDIT IT
* Generated by ../../tools/js/generate_spidermonkey_bindings.py on 2012-06-06
*/
#import "js_bindings_NSObject.h"

/*
 * CCDirector
 */
#pragma mark - CCDirector


#ifdef __cplusplus
extern "C" {
#endif

void JSPROXY_CCDirector_createClass(JSContext *cx, JSObject* globalObj, const char* name );

extern JSObject *JSPROXY_CCDirector_object;
extern JSClass *JSPROXY_CCDirector_class;

#ifdef __cplusplus
}
#endif


/* Proxy class */
@interface JSPROXY_CCDirector : JSPROXY_NSObject
{
}

@end
