/*
* AUTOGENERATED FILE. DO NOT EDIT IT
* Generated by ../../tools/js/generate_spidermonkey_bindings.py on 2012-05-31
*/

#import "js_bindings_CCMoveTo.h"

#import "js_bindings_CCActionInterval.h"

extern JSObject *JSPROXY_CCMoveTo_object;
extern JSClass *JSPROXY_CCMoveTo_class;

/* Proxy class */
@interface JSPROXY_CCMoveTo : JSPROXY_CCActionInterval
{
}

@end
