/*
* AUTOGENERATED FILE. DO NOT EDIT IT
* Generated by "generate_spidermonkey_bindings.py -c CocosDenshion_spidermonkey.ini" on 2012-07-10
*/
JSPROXY_SimpleAudioEngine_createClass(_cx, CocosDenshion, "AudioEngine");
