/*
* AUTOGENERATED FILE. DO NOT EDIT IT
* Generated by ../../tools/js/generate_spidermonkey_bindings.py on 2012-06-27
*/
#import "js_bindings_NSObject.h"

/*
 * CCTouchHandler
 */
#pragma mark - CCTouchHandler


#ifdef __cplusplus
extern "C" {
#endif

void JSPROXY_CCTouchHandler_createClass(JSContext *cx, JSObject* globalObj, const char* name );

extern JSObject *JSPROXY_CCTouchHandler_object;
extern JSClass *JSPROXY_CCTouchHandler_class;

#ifdef __cplusplus
}
#endif


/* Proxy class */
@interface JSPROXY_CCTouchHandler : JSPROXY_NSObject
{
}

@end

/*
 * CCNode
 */
#pragma mark - CCNode


#ifdef __cplusplus
extern "C" {
#endif

void JSPROXY_CCNode_createClass(JSContext *cx, JSObject* globalObj, const char* name );

extern JSObject *JSPROXY_CCNode_object;
extern JSClass *JSPROXY_CCNode_class;

#ifdef __cplusplus
}
#endif


/* Proxy class */
@interface JSPROXY_CCNode : JSPROXY_NSObject
{
}

@end

/*
 * CCMenuItem
 */
#pragma mark - CCMenuItem


#ifdef __cplusplus
extern "C" {
#endif

void JSPROXY_CCMenuItem_createClass(JSContext *cx, JSObject* globalObj, const char* name );

extern JSObject *JSPROXY_CCMenuItem_object;
extern JSClass *JSPROXY_CCMenuItem_class;

#ifdef __cplusplus
}
#endif


/* Proxy class */
@interface JSPROXY_CCMenuItem : JSPROXY_CCNode
{
}

@end

/*
 * CCMenuItemLabel
 */
#pragma mark - CCMenuItemLabel


#ifdef __cplusplus
extern "C" {
#endif

void JSPROXY_CCMenuItemLabel_createClass(JSContext *cx, JSObject* globalObj, const char* name );

extern JSObject *JSPROXY_CCMenuItemLabel_object;
extern JSClass *JSPROXY_CCMenuItemLabel_class;

#ifdef __cplusplus
}
#endif


/* Proxy class */
@interface JSPROXY_CCMenuItemLabel : JSPROXY_CCMenuItem
{
}

@end

/*
 * CCMenuItemAtlasFont
 */
#pragma mark - CCMenuItemAtlasFont


#ifdef __cplusplus
extern "C" {
#endif

void JSPROXY_CCMenuItemAtlasFont_createClass(JSContext *cx, JSObject* globalObj, const char* name );

extern JSObject *JSPROXY_CCMenuItemAtlasFont_object;
extern JSClass *JSPROXY_CCMenuItemAtlasFont_class;

#ifdef __cplusplus
}
#endif


/* Proxy class */
@interface JSPROXY_CCMenuItemAtlasFont : JSPROXY_CCMenuItemLabel
{
}

@end

/*
 * CCTMXObjectGroup
 */
#pragma mark - CCTMXObjectGroup


#ifdef __cplusplus
extern "C" {
#endif

void JSPROXY_CCTMXObjectGroup_createClass(JSContext *cx, JSObject* globalObj, const char* name );

extern JSObject *JSPROXY_CCTMXObjectGroup_object;
extern JSClass *JSPROXY_CCTMXObjectGroup_class;

#ifdef __cplusplus
}
#endif


/* Proxy class */
@interface JSPROXY_CCTMXObjectGroup : JSPROXY_NSObject
{
}

@end

/*
 * CCAction
 */
#pragma mark - CCAction


#ifdef __cplusplus
extern "C" {
#endif

void JSPROXY_CCAction_createClass(JSContext *cx, JSObject* globalObj, const char* name );

extern JSObject *JSPROXY_CCAction_object;
extern JSClass *JSPROXY_CCAction_class;

#ifdef __cplusplus
}
#endif


/* Proxy class */
@interface JSPROXY_CCAction : JSPROXY_NSObject
{
}

@end

/*
 * CCFiniteTimeAction
 */
#pragma mark - CCFiniteTimeAction


#ifdef __cplusplus
extern "C" {
#endif

void JSPROXY_CCFiniteTimeAction_createClass(JSContext *cx, JSObject* globalObj, const char* name );

extern JSObject *JSPROXY_CCFiniteTimeAction_object;
extern JSClass *JSPROXY_CCFiniteTimeAction_class;

#ifdef __cplusplus
}
#endif


/* Proxy class */
@interface JSPROXY_CCFiniteTimeAction : JSPROXY_CCAction
{
}

@end

/*
 * CCActionInterval
 */
#pragma mark - CCActionInterval


#ifdef __cplusplus
extern "C" {
#endif

void JSPROXY_CCActionInterval_createClass(JSContext *cx, JSObject* globalObj, const char* name );

extern JSObject *JSPROXY_CCActionInterval_object;
extern JSClass *JSPROXY_CCActionInterval_class;

#ifdef __cplusplus
}
#endif


/* Proxy class */
@interface JSPROXY_CCActionInterval : JSPROXY_CCFiniteTimeAction
{
}

@end

/*
 * CCMoveTo
 */
#pragma mark - CCMoveTo


#ifdef __cplusplus
extern "C" {
#endif

void JSPROXY_CCMoveTo_createClass(JSContext *cx, JSObject* globalObj, const char* name );

extern JSObject *JSPROXY_CCMoveTo_object;
extern JSClass *JSPROXY_CCMoveTo_class;

#ifdef __cplusplus
}
#endif


/* Proxy class */
@interface JSPROXY_CCMoveTo : JSPROXY_CCActionInterval
{
}

@end

/*
 * CCMoveBy
 */
#pragma mark - CCMoveBy


#ifdef __cplusplus
extern "C" {
#endif

void JSPROXY_CCMoveBy_createClass(JSContext *cx, JSObject* globalObj, const char* name );

extern JSObject *JSPROXY_CCMoveBy_object;
extern JSClass *JSPROXY_CCMoveBy_class;

#ifdef __cplusplus
}
#endif


/* Proxy class */
@interface JSPROXY_CCMoveBy : JSPROXY_CCMoveTo
{
}

@end

/*
 * CCAccelDeccelAmplitude
 */
#pragma mark - CCAccelDeccelAmplitude


#ifdef __cplusplus
extern "C" {
#endif

void JSPROXY_CCAccelDeccelAmplitude_createClass(JSContext *cx, JSObject* globalObj, const char* name );

extern JSObject *JSPROXY_CCAccelDeccelAmplitude_object;
extern JSClass *JSPROXY_CCAccelDeccelAmplitude_class;

#ifdef __cplusplus
}
#endif


/* Proxy class */
@interface JSPROXY_CCAccelDeccelAmplitude : JSPROXY_CCActionInterval
{
}

@end

/*
 * CCReverseTime
 */
#pragma mark - CCReverseTime


#ifdef __cplusplus
extern "C" {
#endif

void JSPROXY_CCReverseTime_createClass(JSContext *cx, JSObject* globalObj, const char* name );

extern JSObject *JSPROXY_CCReverseTime_object;
extern JSClass *JSPROXY_CCReverseTime_class;

#ifdef __cplusplus
}
#endif


/* Proxy class */
@interface JSPROXY_CCReverseTime : JSPROXY_CCActionInterval
{
}

@end

/*
 * CCSprite
 */
#pragma mark - CCSprite


#ifdef __cplusplus
extern "C" {
#endif

void JSPROXY_CCSprite_createClass(JSContext *cx, JSObject* globalObj, const char* name );

extern JSObject *JSPROXY_CCSprite_object;
extern JSClass *JSPROXY_CCSprite_class;

#ifdef __cplusplus
}
#endif


/* Proxy class */
@interface JSPROXY_CCSprite : JSPROXY_CCNode
{
}

@end

/*
 * ChipmunkSprite
 */
#pragma mark - ChipmunkSprite


#ifdef __cplusplus
extern "C" {
#endif

void JSPROXY_ChipmunkSprite_createClass(JSContext *cx, JSObject* globalObj, const char* name );

extern JSObject *JSPROXY_ChipmunkSprite_object;
extern JSClass *JSPROXY_ChipmunkSprite_class;

#ifdef __cplusplus
}
#endif


/* Proxy class */
@interface JSPROXY_ChipmunkSprite : JSPROXY_CCSprite
{
}

@end

/*
 * CCLayer
 */
#pragma mark - CCLayer


#ifdef __cplusplus
extern "C" {
#endif

void JSPROXY_CCLayer_createClass(JSContext *cx, JSObject* globalObj, const char* name );

extern JSObject *JSPROXY_CCLayer_object;
extern JSClass *JSPROXY_CCLayer_class;

#ifdef __cplusplus
}
#endif


/* Proxy class */
@interface JSPROXY_CCLayer : JSPROXY_CCNode
{
}

@end

/*
 * CCLayerColor
 */
#pragma mark - CCLayerColor


#ifdef __cplusplus
extern "C" {
#endif

void JSPROXY_CCLayerColor_createClass(JSContext *cx, JSObject* globalObj, const char* name );

extern JSObject *JSPROXY_CCLayerColor_object;
extern JSClass *JSPROXY_CCLayerColor_class;

#ifdef __cplusplus
}
#endif


/* Proxy class */
@interface JSPROXY_CCLayerColor : JSPROXY_CCLayer
{
}

@end

/*
 * CCProgressTo
 */
#pragma mark - CCProgressTo


#ifdef __cplusplus
extern "C" {
#endif

void JSPROXY_CCProgressTo_createClass(JSContext *cx, JSObject* globalObj, const char* name );

extern JSObject *JSPROXY_CCProgressTo_object;
extern JSClass *JSPROXY_CCProgressTo_class;

#ifdef __cplusplus
}
#endif


/* Proxy class */
@interface JSPROXY_CCProgressTo : JSPROXY_CCActionInterval
{
}

@end

/*
 * CCScene
 */
#pragma mark - CCScene


#ifdef __cplusplus
extern "C" {
#endif

void JSPROXY_CCScene_createClass(JSContext *cx, JSObject* globalObj, const char* name );

extern JSObject *JSPROXY_CCScene_object;
extern JSClass *JSPROXY_CCScene_class;

#ifdef __cplusplus
}
#endif


/* Proxy class */
@interface JSPROXY_CCScene : JSPROXY_CCNode
{
}

@end

/*
 * CCActionInstant
 */
#pragma mark - CCActionInstant


#ifdef __cplusplus
extern "C" {
#endif

void JSPROXY_CCActionInstant_createClass(JSContext *cx, JSObject* globalObj, const char* name );

extern JSObject *JSPROXY_CCActionInstant_object;
extern JSClass *JSPROXY_CCActionInstant_class;

#ifdef __cplusplus
}
#endif


/* Proxy class */
@interface JSPROXY_CCActionInstant : JSPROXY_CCFiniteTimeAction
{
}

@end

/*
 * CCFlipX
 */
#pragma mark - CCFlipX


#ifdef __cplusplus
extern "C" {
#endif

void JSPROXY_CCFlipX_createClass(JSContext *cx, JSObject* globalObj, const char* name );

extern JSObject *JSPROXY_CCFlipX_object;
extern JSClass *JSPROXY_CCFlipX_class;

#ifdef __cplusplus
}
#endif


/* Proxy class */
@interface JSPROXY_CCFlipX : JSPROXY_CCActionInstant
{
}

@end

/*
 * CCFlipY
 */
#pragma mark - CCFlipY


#ifdef __cplusplus
extern "C" {
#endif

void JSPROXY_CCFlipY_createClass(JSContext *cx, JSObject* globalObj, const char* name );

extern JSObject *JSPROXY_CCFlipY_object;
extern JSClass *JSPROXY_CCFlipY_class;

#ifdef __cplusplus
}
#endif


/* Proxy class */
@interface JSPROXY_CCFlipY : JSPROXY_CCActionInstant
{
}

@end

/*
 * CCGridAction
 */
#pragma mark - CCGridAction


#ifdef __cplusplus
extern "C" {
#endif

void JSPROXY_CCGridAction_createClass(JSContext *cx, JSObject* globalObj, const char* name );

extern JSObject *JSPROXY_CCGridAction_object;
extern JSClass *JSPROXY_CCGridAction_class;

#ifdef __cplusplus
}
#endif


/* Proxy class */
@interface JSPROXY_CCGridAction : JSPROXY_CCActionInterval
{
}

@end

/*
 * CCTiledGrid3DAction
 */
#pragma mark - CCTiledGrid3DAction


#ifdef __cplusplus
extern "C" {
#endif

void JSPROXY_CCTiledGrid3DAction_createClass(JSContext *cx, JSObject* globalObj, const char* name );

extern JSObject *JSPROXY_CCTiledGrid3DAction_object;
extern JSClass *JSPROXY_CCTiledGrid3DAction_class;

#ifdef __cplusplus
}
#endif


/* Proxy class */
@interface JSPROXY_CCTiledGrid3DAction : JSPROXY_CCGridAction
{
}

@end

/*
 * CCShakyTiles3D
 */
#pragma mark - CCShakyTiles3D


#ifdef __cplusplus
extern "C" {
#endif

void JSPROXY_CCShakyTiles3D_createClass(JSContext *cx, JSObject* globalObj, const char* name );

extern JSObject *JSPROXY_CCShakyTiles3D_object;
extern JSClass *JSPROXY_CCShakyTiles3D_class;

#ifdef __cplusplus
}
#endif


/* Proxy class */
@interface JSPROXY_CCShakyTiles3D : JSPROXY_CCTiledGrid3DAction
{
}

@end

/*
 * CCJumpBy
 */
#pragma mark - CCJumpBy


#ifdef __cplusplus
extern "C" {
#endif

void JSPROXY_CCJumpBy_createClass(JSContext *cx, JSObject* globalObj, const char* name );

extern JSObject *JSPROXY_CCJumpBy_object;
extern JSClass *JSPROXY_CCJumpBy_class;

#ifdef __cplusplus
}
#endif


/* Proxy class */
@interface JSPROXY_CCJumpBy : JSPROXY_CCActionInterval
{
}

@end

/*
 * CCLabelTTF
 */
#pragma mark - CCLabelTTF


#ifdef __cplusplus
extern "C" {
#endif

void JSPROXY_CCLabelTTF_createClass(JSContext *cx, JSObject* globalObj, const char* name );

extern JSObject *JSPROXY_CCLabelTTF_object;
extern JSClass *JSPROXY_CCLabelTTF_class;

#ifdef __cplusplus
}
#endif


/* Proxy class */
@interface JSPROXY_CCLabelTTF : JSPROXY_CCSprite
{
}

@end

/*
 * CCProgressFromTo
 */
#pragma mark - CCProgressFromTo


#ifdef __cplusplus
extern "C" {
#endif

void JSPROXY_CCProgressFromTo_createClass(JSContext *cx, JSObject* globalObj, const char* name );

extern JSObject *JSPROXY_CCProgressFromTo_object;
extern JSClass *JSPROXY_CCProgressFromTo_class;

#ifdef __cplusplus
}
#endif


/* Proxy class */
@interface JSPROXY_CCProgressFromTo : JSPROXY_CCActionInterval
{
}

@end

/*
 * CCShaderCache
 */
#pragma mark - CCShaderCache


#ifdef __cplusplus
extern "C" {
#endif

void JSPROXY_CCShaderCache_createClass(JSContext *cx, JSObject* globalObj, const char* name );

extern JSObject *JSPROXY_CCShaderCache_object;
extern JSClass *JSPROXY_CCShaderCache_class;

#ifdef __cplusplus
}
#endif


/* Proxy class */
@interface JSPROXY_CCShaderCache : JSPROXY_NSObject
{
}

@end

/*
 * CCTransitionScene
 */
#pragma mark - CCTransitionScene


#ifdef __cplusplus
extern "C" {
#endif

void JSPROXY_CCTransitionScene_createClass(JSContext *cx, JSObject* globalObj, const char* name );

extern JSObject *JSPROXY_CCTransitionScene_object;
extern JSClass *JSPROXY_CCTransitionScene_class;

#ifdef __cplusplus
}
#endif


/* Proxy class */
@interface JSPROXY_CCTransitionScene : JSPROXY_CCScene
{
}

@end

/*
 * CCTransitionFadeTR
 */
#pragma mark - CCTransitionFadeTR


#ifdef __cplusplus
extern "C" {
#endif

void JSPROXY_CCTransitionFadeTR_createClass(JSContext *cx, JSObject* globalObj, const char* name );

extern JSObject *JSPROXY_CCTransitionFadeTR_object;
extern JSClass *JSPROXY_CCTransitionFadeTR_class;

#ifdef __cplusplus
}
#endif


/* Proxy class */
@interface JSPROXY_CCTransitionFadeTR : JSPROXY_CCTransitionScene
{
}

@end

/*
 * CCScaleTo
 */
#pragma mark - CCScaleTo


#ifdef __cplusplus
extern "C" {
#endif

void JSPROXY_CCScaleTo_createClass(JSContext *cx, JSObject* globalObj, const char* name );

extern JSObject *JSPROXY_CCScaleTo_object;
extern JSClass *JSPROXY_CCScaleTo_class;

#ifdef __cplusplus
}
#endif


/* Proxy class */
@interface JSPROXY_CCScaleTo : JSPROXY_CCActionInterval
{
}

@end

/*
 * CCScaleBy
 */
#pragma mark - CCScaleBy


#ifdef __cplusplus
extern "C" {
#endif

void JSPROXY_CCScaleBy_createClass(JSContext *cx, JSObject* globalObj, const char* name );

extern JSObject *JSPROXY_CCScaleBy_object;
extern JSClass *JSPROXY_CCScaleBy_class;

#ifdef __cplusplus
}
#endif


/* Proxy class */
@interface JSPROXY_CCScaleBy : JSPROXY_CCScaleTo
{
}

@end

/*
 * CCSequence
 */
#pragma mark - CCSequence


#ifdef __cplusplus
extern "C" {
#endif

void JSPROXY_CCSequence_createClass(JSContext *cx, JSObject* globalObj, const char* name );

extern JSObject *JSPROXY_CCSequence_object;
extern JSClass *JSPROXY_CCSequence_class;

#ifdef __cplusplus
}
#endif


/* Proxy class */
@interface JSPROXY_CCSequence : JSPROXY_CCActionInterval
{
}

@end

/*
 * CCDirector
 */
#pragma mark - CCDirector


#ifdef __cplusplus
extern "C" {
#endif

void JSPROXY_CCDirector_createClass(JSContext *cx, JSObject* globalObj, const char* name );

extern JSObject *JSPROXY_CCDirector_object;
extern JSClass *JSPROXY_CCDirector_class;

#ifdef __cplusplus
}
#endif


/* Proxy class */
@interface JSPROXY_CCDirector : JSPROXY_NSObject
{
}

@end
