/*
* AUTOGENERATED FILE. DO NOT EDIT IT
* Generated by "generate_spidermonkey_bindings.py -c CocosBuilderReader_spidermonkey.ini" on 2012-07-24
*/
JSPROXY_CCBReader_createClass(_cx, CocosBuilderReader, "Reader");
