/*
* AUTOGENERATED FILE. DO NOT EDIT IT
* Generated by ../../tools/js/generate_spidermonkey_bindings.py on 2012-05-30
*/

#import "js_bindings_CCMoveBy.h"

#import "js_bindings_CCMoveTo.h"

extern JSObject *JSPROXY_CCMoveBy_object;
extern JSClass *JSPROXY_CCMoveBy_class;

/* Proxy class */
@interface JSPROXY_CCMoveBy : JSPROXY_CCMoveTo
{
}

@end
