/*
* AUTOGENERATED FILE. DO NOT EDIT IT
* Generated by ../../tools/js/generate_spidermonkey_bindings.py on 2012-05-31
*/
#import "js_bindings_CCDirector.h"
#import "js_bindings_CCMoveTo.h"
#import "js_bindings_CCLayer.h"
#import "js_bindings_CCActionInterval.h"
#import "js_bindings_CCNode.h"
#import "js_bindings_CCMoveBy.h"
#import "js_bindings_CCScaleTo.h"
#import "js_bindings_CCScene.h"
#import "js_bindings_CCFiniteTimeAction.h"
#import "js_bindings_CCAction.h"
#import "js_bindings_NSObject.h"
#import "js_bindings_CCScaleBy.h"
#import "js_bindings_CCSprite.h"
#import "js_bindings_CCRotateBy.h"
