/*
* AUTOGENERATED FILE. DO NOT EDIT IT
* Generated by ../../tools/js/generate_spidermonkey_bindings.py on 2012-05-31
*/

// needed for callbacks from objective-c to JS
#import <objc/runtime.h>
#import "JRSwizzle.h"

#import "jstypedarray.h"
#import "ScriptingCore.h"   

#import "js_bindings_CCParticleSystemQuad.h"
#import "js_bindings_cocos2d.h"


JSClass* JSPROXY_CCParticleSystemQuad_class = NULL;
JSObject* JSPROXY_CCParticleSystemQuad_object = NULL;
 // Constructor
JSBool JSPROXY_CCParticleSystemQuad_constructor(JSContext *cx, uint32_t argc, jsval *vp)
{
    JSObject *jsobj = JS_NewObject(cx, JSPROXY_CCParticleSystemQuad_class, JSPROXY_CCParticleSystemQuad_object, NULL);

    JSPROXY_CCParticleSystemQuad *proxy = [[JSPROXY_CCParticleSystemQuad alloc] initWithJSObject:jsobj];

    JS_SetPrivate(jsobj, proxy);
    JS_SET_RVAL(cx, vp, OBJECT_TO_JSVAL(jsobj));

    /* no callbacks */
    
    return JS_TRUE;
}

// Destructor
void JSPROXY_CCParticleSystemQuad_finalize(JSContext *cx, JSObject *obj)
{
	JSPROXY_CCParticleSystemQuad *pt = (JSPROXY_CCParticleSystemQuad*)JS_GetPrivate(obj);
	if (pt) {
		// id real = [pt realObj];
	
		/* no callbacks */

		[pt release];

		JS_free(cx, pt);
	}
}

// Arguments: 
// Ret value: None
JSBool JSPROXY_CCParticleSystemQuad_initIndices(JSContext *cx, uint32_t argc, jsval *vp) {

	JSObject* obj = (JSObject *)JS_THIS_OBJECT(cx, vp);
	JSPROXY_NSObject *proxy = (JSPROXY_NSObject*) JS_GetPrivate( obj );
	NSCAssert( proxy, @"Invalid Proxy object");
	NSCAssert( [proxy realObj], @"Object not initialzied. error");
	NSCAssert( argc == 0, @"Invalid number of arguments" );

	CCParticleSystemQuad *real = (CCParticleSystemQuad*) [proxy realObj];
	[real initIndices ];
	JS_SET_RVAL(cx, vp, JSVAL_TRUE);
	return JS_TRUE;
}

@implementation JSPROXY_CCParticleSystemQuad

+(void) createClassWithContext:(JSContext*)cx object:(JSObject*)globalObj name:(NSString*)name
{
	JSPROXY_CCParticleSystemQuad_class = (JSClass *)calloc(1, sizeof(JSClass));
	JSPROXY_CCParticleSystemQuad_class->name = [name UTF8String];
	JSPROXY_CCParticleSystemQuad_class->addProperty = JS_PropertyStub;
	JSPROXY_CCParticleSystemQuad_class->delProperty = JS_PropertyStub;
	JSPROXY_CCParticleSystemQuad_class->getProperty = JS_PropertyStub;
	JSPROXY_CCParticleSystemQuad_class->setProperty = JS_StrictPropertyStub;
	JSPROXY_CCParticleSystemQuad_class->enumerate = JS_EnumerateStub;
	JSPROXY_CCParticleSystemQuad_class->resolve = JS_ResolveStub;
	JSPROXY_CCParticleSystemQuad_class->convert = JS_ConvertStub;
	JSPROXY_CCParticleSystemQuad_class->finalize = JSPROXY_CCParticleSystemQuad_finalize;
	JSPROXY_CCParticleSystemQuad_class->flags = JSCLASS_HAS_PRIVATE;

	static JSPropertySpec properties[] = {
		{0, 0, 0, 0, 0}
	};
	static JSFunctionSpec funcs[] = {
		JS_FN("initIndices", JSPROXY_CCParticleSystemQuad_initIndices, 1, JSPROP_PERMANENT | JSPROP_SHARED ),
		JS_FS_END
	};
	static JSFunctionSpec st_funcs[] = {
		JS_FS_END
	};

	JSPROXY_CCParticleSystemQuad_object = JS_InitClass(cx, globalObj, JSPROXY_CCParticleSystem_object, JSPROXY_CCParticleSystemQuad_class, JSPROXY_CCParticleSystemQuad_constructor,0,properties,funcs,NULL,st_funcs);
}

@end
