/*
* AUTOGENERATED FILE. DO NOT EDIT IT
* Generated by ../../tools/js/generate_spidermonkey_bindings.py on 2012-05-30
*/

#import "js_bindings_CCScaleBy.h"

#import "js_bindings_CCScaleTo.h"

extern JSObject *JSPROXY_CCScaleBy_object;
extern JSClass *JSPROXY_CCScaleBy_class;

/* Proxy class */
@interface JSPROXY_CCScaleBy : JSPROXY_CCScaleTo
{
}

@end
