var EnemyType = [
    {
        type:0,
        textureName:"E0.png",
        bulletType:"W2.png",
        HP:1,
        moveType:global.moveType.Vertical,
        attackMode:global.AttackMode.Normal,
        scoreValue:15
    },
    {
        type:1,
        textureName:"E1.png",
        bulletType:"W2.png",
        HP:2,
        moveType:global.moveType.Attack,
        attackMode:global.AttackMode.Normal,
        scoreValue:40
    },
    {
        type:2,
        textureName:"E2.png",
        bulletType:"W2.png",
        HP:4,
        moveType:global.moveType.Horizontal,
        attackMode:global.AttackMode.Tsuihikidan,
        scoreValue:60
    },
    {
        type:3,
        textureName:"E3.png",
        bulletType:"W2.png",
        HP:6,
        moveType:global.moveType.Overlap,
        attackMode:global.AttackMode.Normal,
        scoreValue:80
    },
    {
        type:4,
        textureName:"E4.png",
        bulletType:"W2.png",
        HP:10,
        moveType:global.moveType.Horizontal,
        attackMode:global.AttackMode.Tsuihikidan,
        scoreValue:150
    },
    {
        type:5,
        textureName:"E5.png",
        bulletType:"W2.png",
        HP:15,
        moveType:global.moveType.Horizontal,
        attackMode:global.AttackMode.Normal,
        scoreValue:200
    }
]
