/*
* AUTOGENERATED FILE. DO NOT EDIT IT
* Generated by "generate_js_bindings.py -c cocos2d_spidermonkey.ini" on 2012-08-13
*/
#import "js_bindings_config.h"
#ifdef JSB_INCLUDE_COCOS2D_IOS

JSPROXY_CCDirector_createClass(_cx, cocos2d_ios, "Director");
JSPROXY_CCDirectorIOS_createClass(_cx, cocos2d_ios, "DirectorIOS");
JSPROXY_CCDirectorDisplayLink_createClass(_cx, cocos2d_ios, "DirectorDisplayLink");
JSPROXY_CCLayer_createClass(_cx, cocos2d_ios, "Layer");
JSPROXY_CCLayerMultiplex_createClass(_cx, cocos2d_ios, "LayerMultiplex");
JSPROXY_CCLayerColor_createClass(_cx, cocos2d_ios, "LayerColor");
JSPROXY_CCLayerGradient_createClass(_cx, cocos2d_ios, "LayerGradient");
JSPROXY_CCMenu_createClass(_cx, cocos2d_ios, "Menu");


#endif // JSB_INCLUDE_COCOS2D_IOS
