/*
* AUTOGENERATED FILE. DO NOT EDIT IT
* Generated by "generate_js_bindings.py -c CocosBuilderReader_spidermonkey.ini" on 2012-08-13
*/
#import "js_bindings_config.h"
#ifdef JSB_INCLUDE_COCOSBUILDERREADER

JSPROXY_CCBReader_createClass(_cx, CocosBuilderReader, "Reader");


#endif // JSB_INCLUDE_COCOSBUILDERREADER
