/*
* AUTOGENERATED FILE. DO NOT EDIT IT
* Generated by "generate_js_bindings.py -c CocosDenshion_spidermonkey.ini" on 2012-08-13
*/
#import "js_bindings_config.h"
#ifdef JSB_INCLUDE_COCOSDENSHION



#endif // JSB_INCLUDE_COCOSDENSHION
